@hostname = {{$dotenv HOST}}
@port = {{$dotenv PORT}}
@baseUrl = http://{{hostname}}:{{port}}

### Health Check
GET {{baseUrl}}/api/v1

### DEBUG - Seed Test User
POST {{baseUrl}}/api/v1/debug/seed-user

### DEBUG - Seed Species (Mochi)
POST {{baseUrl}}/api/v1/debug/seed-species


### Pomodoro - END (completó 25 minutos - gana monedas)
POST {{baseUrl}}/api/v1/pomodoro/end
Content-Type: application/json

{
  "userId": 1,
  "type": "session",
  "minutesCompleted": 25
}

### Pets - BUY EGG (Mochi: 25 monedas)
POST {{baseUrl}}/api/v1/pets/buy-egg
Content-Type: application/json

{
  "userId": 1,
  "speciesId": 1
}

### Pets - HATCH EGG
POST {{baseUrl}}/api/v1/pets/hatch
Content-Type: application/json

{
  "userId": 1,
  "eggId": 2
}
